version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: global/dockerhub/token:username
    DOCKERHUB_TOKEN: global/dockerhub/token:token

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --secret id=npmtoken,env=NPM_TOKEN -t $PROJECT_NAME -f Dockerfile .
      - docker tag $PROJECT_NAME $REPOSITORY_URL:$IMAGE_TAG
      - docker tag $PROJECT_NAME $REPOSITORY_URL:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URL:latest
      - docker push $REPOSITORY_URL:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $ENV-$PROJECT_NAME $REPOSITORY_URL:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - '*'
    - imagedefinitions.json