#!/bin/bash

# This script contains setup tasks that are common to all development environments,
# whether they are running locally on Windows or in a GitHub Codespace. It handles
# environment-agnostic configurations like setting up Git safe directories and launching Docker services.

set -e
echo "--- 🚀 Executing Common Setup Tasks for sentinel ---"

# Pre-task: Install dependencies, including AI CLIs
echo "  ---> Installing dependencies, including AI CLIs..."
bash /var/www/scripts/setup-dependencies.sh

# --- Task 1: Configure the shell profile for first run ---
# Adds logic to .bashrc to run our interactive script only once.
BASHRC_SETUP_BLOCK="# [AUTOGENERATED] First time interactive setup"
if ! grep -q "$BASHRC_SETUP_BLOCK" /root/.bashrc; then
    echo "🔄 Scheduling interactive setup and persistent configs for the first terminal session..."
    tee -a /root/.bashrc > /dev/null << 'EOF'

# [AUTOGENERATED] First time interactive setup
if [ ! -f ~/.devcontainer-first-run-complete ]; then
    bash /var/www/scripts/interactive-setup.sh
fi

# [AUTOGENERATED] Unset GITHUB_TOKEN to allow interactive 'gh auth login'.
# This is necessary in environments like GitHub Codespaces where GITHUB_TOKEN is set by default.
unset GITHUB_TOKEN

# [AUTOGENERATED] SSH Agent and Permissions Fix Start
# Fix permissions for Docker Desktop on Windows mounts.
if [ -d "$HOME/.ssh" ]; then
    chmod 700 "$HOME/.ssh"
fi
if [ -f "$HOME/.ssh/config" ]; then
    chmod 600 "$HOME/.ssh/config"
fi
if [ -f "$HOME/.ssh/id_rsa" ]; then
    chmod 600 "$HOME/.ssh/id_rsa"
fi

# Start ssh-agent and add key.
if [ -z "$SSH_AUTH_SOCK" ]; then
   eval "$(ssh-agent -s)" > /dev/null
fi
if [ -f "$HOME/.ssh/id_rsa" ] && ! ssh-add -l | grep -q "$(ssh-keygen -lf $HOME/.ssh/id_rsa 2>/dev/null | awk '{print $2}')"; then
    ssh-add "$HOME/.ssh/id_rsa" &> /dev/null
fi
# [AUTOGENERATED] SSH Agent and Permissions Fix End
EOF
    echo "✅ Interactive setup and persistent configs scheduled."
fi

# --- Task 2: Configure Git for safe directory access ---
echo "🔄 [T2] Configuring Git safe directory..."
git config --global --add safe.directory /var/www
echo "✅ [T2] Git safe directory configured."

echo "--- ✅ sentinel Common Setup Finished ---"